services:
  - type: web
    name: ejm-santos-site
    env: python
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt && python init_render.py
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    envVars:
      - key: EJM_SECRET
        sync: false
      - key: FLASK_ENV
        value: production
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: PUBLIC_BASE_URL
        value: https://ejm-santos-site-1.onrender.com
